# Generated by Streamlit Notebook
# Original notebook: dynamic_cell_control_demo_1
# This file can be run directly with: streamlit run <filename>

from streamlit_notebook import notebook
import streamlit as st

st.set_page_config(page_title="st.notebook", layout="centered", initial_sidebar_state="collapsed")

nb = notebook(title='dynamic_cell_control_demo_1')

@nb.cell(type='code', reactive=True, fragment=False)
def cell_0():
    if st.button("click me"):
        __notebook__.cells[1].run()

@nb.cell(type='code', reactive=False, fragment=False)
def cell_1():
    import time
    for i in range(10):
        time.sleep(0.5)
        print(i)

# Render the notebook
nb.render()