# Generated by Streamlit Notebook
# Original notebook: dynamic_cell_control_demo_1
# This file can be run directly with: streamlit run <filename>

from streamlit_notebook import get_notebook, render_notebook
import streamlit as st

st.set_page_config(page_title="st.notebook", layout="centered", initial_sidebar_state="collapsed")

nb = get_notebook(title='dynamic_cell_control_demo_1')

@nb.cell(type='code', auto_rerun=True, fragment=False)
def cell_0():
    if st.button("click me"):
        notebook.cells[1].run()

@nb.cell(type='code', auto_rerun=False, fragment=False)
def cell_1():
    import time
    for i in range(10):
        time.sleep(0.5)
        print(i)

# Render the notebook
# Using render_notebook() instead of nb.render() allows the notebook
# to be replaced dynamically (e.g., when loading a different file)
render_notebook()