# Generated by Streamlit Notebook
# Original notebook: dynamic_cell_control_demo_2
# This file can be run directly with: streamlit run <filename>

from streamlit_notebook import get_notebook, render_notebook
import streamlit as st

st.set_page_config(page_title="st.notebook", layout="centered", initial_sidebar_state="collapsed")

nb = get_notebook(title='dynamic_cell_control_demo_2')

@nb.cell(type='code', auto_rerun=False, fragment=False)
def cell_0():
    code="""
    cell2=__notebook__.new_cell(code="print('hello')")
    cell2.run()
    """

    cell1=__notebook__.new_cell(code=code)
    cell1.run()

    #Run this cell

# Render the notebook
# Using render_notebook() instead of nb.render() allows the notebook
# to be replaced dynamically (e.g., when loading a different file)
render_notebook()