# Generated by Streamlit Notebook
# Original notebook: interactive_plot_demo
# This file can be run directly with: streamlit run <filename>

from streamlit_notebook import get_notebook, render_notebook
import streamlit as st

st.set_page_config(page_title="st.notebook", layout="centered", initial_sidebar_state="collapsed")

nb = get_notebook(title='interactive_plot_demo')

@nb.cell(type='markdown', auto_rerun=True, fragment=False)
def cell_0():
    r'''
    ### Plot of the function:
    $$
    f(x)=x^{<<st.session_state.myslider>>},\ \forall x\in [0,1]
    $$
    '''

@nb.cell(type='code', auto_rerun=False, fragment=False)
def cell_1():
    import numpy as np
    import matplotlib.pyplot as plt
    x=np.linspace(0,1,200)

@nb.cell(type='code', auto_rerun=True, fragment=False)
def cell_2():
    n=st.slider("Exponent",0.0,2.0,1.0,key="myslider")

@nb.cell(type='code', auto_rerun=True, fragment=False)
def cell_3():
    plt.plot(x,x**n);
    st.pyplot(plt.gcf());

# Render the notebook
# Using render_notebook() instead of nb.render() allows the notebook
# to be replaced dynamically (e.g., when loading a different file)
render_notebook()