# Generated by Streamlit Notebook
# Original notebook: interactive_plot_demo
# This file can be run directly with: streamlit run <filename>

from streamlit_notebook import st_notebook
import streamlit as st

nb = st_notebook(title='interactive_plot_demo')

@nb.cell(type='markdown', reactive=True, fragment=False)
def cell_0():
    r'''
    ### Plot of the function:
    $$
    f(x)=x^{<<st.session_state.myslider>>},\ \forall x\in [0,1]
    $$
    '''

@nb.cell(type='code', reactive=False, fragment=False)
def cell_1():
    import numpy as np
    import matplotlib.pyplot as plt
    x=np.linspace(0,1,200)

@nb.cell(type='code', reactive=True, fragment=False)
def cell_2():
    n=st.slider("Exponent",0.0,2.0,1.0,key="myslider")

@nb.cell(type='code', reactive=True, fragment=False)
def cell_3():
    plt.plot(x,x**n);
    st.pyplot(plt.gcf());

# Render the notebook
nb.render()